### ISSUE TITLE
Update to Catppuccin 0.2.0

### ISSUE THREAD

**Issue by Kaishiyoku** [catppuccin/jetbrains#10]
The color theme looks awesome! Are there any plans for a light theme?

**Comment by mip29** [comment]
If you look at the homepage for the theme (https://github.com/catppuccin/catppuccin), you'll see that there a v2 of catppuccin which has 4 themes, including 1 light theme. Currently, it still needs to be ported to jetbrains IDEs.

**Comment by shiveenp** [comment]
+1 for light theme 👍 Are contribs welcome? I am happy to do it in some free time

**Comment by nekowinston** [comment]
#15 aims to implement this, and we currently have a [v0.2.0](https://github.com/catppuccin/jetbrains/tree/v0.2.0) branch on this repository, from which we created this preview pre-release:
[Catppuccin_Theme-0.2.0-alpha-preview.jar](https://cdn.discordapp.com/attachments/1020275395133710336/1027377133955338320/Catppuccin_Theme-0.2.0-alpha-preview.jar) (apologies for the Discord CDN download, I'll try to get it somewhere else soon)

**Comment by sgoudham** [comment]
Just want to let everyone know that progress is currently being tracked here on this comment!
- https://github.com/catppuccin/jetbrains/pull/15#issuecomment-1279855988
