### ISSUE TITLE
No highlight for autosuggestion

### ISSUE THREAD

**Issue by AlexanderObolonkov** [catppuccin/jetbrains#100]
There is no highlight for code completion after update. Only after choosing on arrow keys
But at the same time on ctrl + space it works correctly
All Catppuccin themes, PyCharm 2023.2.3
![image](https://github.com/catppuccin/jetbrains/assets/79802354/65d3317a-a170-463c-b51f-2aa8e1d1d7a0)
![image](https://github.com/catppuccin/jetbrains/assets/79802354/1ab43a41-ddb6-4ed1-8396-b16bfb9f4ad4)
On ctrl+space
![image](https://github.com/catppuccin/jetbrains/assets/79802354/ec3ac9f7-56f0-42f5-8b86-80b097d87c86)
Default theme
![image](https://github.com/catppuccin/jetbrains/assets/79802354/30401357-a856-4fc5-a1fc-df48d1f65f38)

**Comment by sgoudham** [comment]
Thanks for raising this issue!

Unfortunately, we also ran into this while testing out the theme during the development of v3. @quentinguidee tried to fix this but they weren't able to. From their testing, they noticed that the "Trash Panda Theme" also had this issue so there may be something in common that is causing this. 

I don't have the time to troubleshoot this at the minute but I'll dig into this when I can!

**Comment by sgoudham** [comment]
So I decided to timebox this today to around half an hour or so... I have managed to fix it but it's _really weird_. 

It seems as though JetBrains now automatically takes control of the shading in the completion pop up. As a result, our existing keys actually seem to be preventing this. 

By changing the `selectionInactiveBackground` to the **same value** as the `selectionBackground`, the shading works properly...

![image](https://github.com/catppuccin/jetbrains/assets/58985301/20fd5f87-dacc-4ede-9e31-7d76bf8e5739)

cc: @quentinguidee
