### ISSUE TITLE
code area is white after update

### ISSUE THREAD

**Issue by JoachimR** [catppuccin/jetbrains#105]
<img width="684" alt="Screenshot 2023-10-24 at 08 27 41" src="https://github.com/catppuccin/jetbrains/assets/2596911/8e79d093-71b2-46a1-ac8a-0a773c7050bd">

after updating to the latest version `3.1.0` the code area is now in light mode. First it only happened on Mocha theme, then after the latest update also the Macchiato theme.

I am using macOS and IntelliJ IDEA 2023.2.3

**Comment by sgoudham** [comment]
Hi 👋 
Please see https://github.com/catppuccin/jetbrains/issues/87#issuecomment-1743872629 and #97

**Comment by JoachimR** [comment]
thank you and sorry for the duplicate 🙏
