### ISSUE TITLE
Darcula theme being applied instead of Dark/New UI theme

### ISSUE THREAD

**Issue by mishyy** [catppuccin/jetbrains#108]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

After updating to v3.2.0, the UI dark mode themes applies the Darcula theme rather than the Dark/New UI-based theme as it had previously done.

This affects Frappe, Macchiato and Mocha; Latte enables light mode and applies the Light with Light Header-based theme as expected.
The editor colour schemes update/apply as expected for all themes in all modes.

#### What I see (Darcula)
<img width="1000" alt="image" src="https://github.com/catppuccin/jetbrains/assets/13673076/782f68d9-8e3f-4f64-afcb-57c3575fcf0e">

#### What I expected to see (Dark/New UI)
<img width="1000" alt="image" src="https://github.com/catppuccin/jetbrains/assets/13673076/fa27506f-d3be-487b-95b6-d14f899388fd">

### What IDE(s) are you seeing the problem on?

IntelliJ IDEA 2023.3 EAP (Ultimate Edition)

**Comment by quentinguidee** [comment]
Isn't that related to the pinned issue?

https://github.com/catppuccin/jetbrains/issues/97

**Comment by mishyy** [comment]
From what I see, no.
As you can see in the screenshots, Catpuccin is selected (and restarts and re-installs were done); and, as noted, the editor colour scheme isn't out of sync with the theme.

**Comment by quentinguidee** [comment]
Oh ok that's the UI, sorry.

I cannot definitely reproduce the issue on the latest EAP. The issue is not here on 2023.2.

**Comment by mishyy** [comment]
It was working fine on EAP before I updated the plugin to 3.2.0.

It's possible, though unlikely, that there was an EAP version update that took effect at the same time.

**Comment by quentinguidee** [comment]
Yep can confirm, it works when downgrading to 3.1.1. As a workaround you can download it from the marketplace in the versions tab. Really strange that it works fine on 2023.2...
