### ISSUE TITLE
Connection colors in Database plugin or DataGrip

### ISSUE THREAD

**Issue by ysooqe** [catppuccin/jetbrains#110]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

The connection colors for database connections in DataGrip (or when using the database plugin) are very dark and look quite similar, which makes it hard to differentiate them:
![Catppuccin Macchiato](https://i.postimg.cc/bpzwpwVt/sw-appy-20231104-113434.png)

In the default dark theme, the colors have much more contrast between them:
![Dark](https://i.postimg.cc/YkdJL2qg/sw-appy-20231104-113710.png)

It would be great if the colors in the Catppuccin Macchiato theme would be more easly distinguishable from each other.

**Comment by sgoudham** [comment]
Hey :wave:,

This is quite an old issue but I've come to realise that the colours here are the same as the ones defined for "File Colors" which recently got updated on the darker flavours to have higher contrast (#162)

![image](https://github.com/user-attachments/assets/593ebc4c-f896-4580-93a5-2a610a3c4099)

I'm going to close this issue as resolved now but if you still find the contrast to be too low, please use the "Custom" colour functionality to define your own colours with whatever you like best. Thanks!
