### ISSUE TITLE
Make Java Interfaces a different Color

### ISSUE THREAD

**Issue by thelooter** [catppuccin/jetbrains#113]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

Currently normal classes, abstract classes and interfaces all have the same color in the editor. Making them different colors makes it easier to spot at a glance what type you are working with

**Comment by sgoudham** [comment]
Hey :wave:, sorry for the long wait on this. 

I feel like this is pretty subjective so I'm hesitant to highlight them differently by default. I'll be closing this as not planned but I may revisit this in the future. 

The great part about Intellij is that the theme editor for languages is actually built-in and can be modified to your liking. If you would like to change Java Interfaces then you can:

1. Navigate to `Settings` -> `Editor` -> `Color Scheme` -> `Java` -> `Classes and Interfaces`
2. Modify the `Foreground` colour to your liking.
3. Click `Apply`.

E.g. Here I'm changing Java Interfaces to `pink`:

![image](https://github.com/catppuccin/jetbrains/assets/58985301/4565d298-82b4-4305-8432-18d0105d1266)

Hope that helps!
