### ISSUE TITLE
Fix text colors in main toolbar

### ISSUE THREAD

**Issue by ftqo** [catppuccin/jetbrains#117]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

The text color in the main toolbar makes the left section unreadable with the new UI.

### Attach screenshots.

![CleanShot 2023-12-17 at 15 53 29](https://github.com/catppuccin/jetbrains/assets/55212219/5c8aa4ba-c2c9-4ec9-95c1-c950b6bf3dcb)
![CleanShot 2023-12-17 at 15 54 10](https://github.com/catppuccin/jetbrains/assets/55212219/9ab8248b-5670-490c-b05d-f51ecf868751)

### What IDE(s) are you seeing the problem on?

IntelliJ IDEA 2023.3.1

**Comment by quentinguidee** [comment]
I can reproduce. I'm wondering if there is even a way to change the color according to the background? 🤔

**Comment by quentinguidee** [comment]
Of course one temporary fix is to right click and change the color, or even hide the custom color, but that doesn't fix the issue

**Comment by ftqo** [comment]
The flare color seems to change when I switch to the "Light with Light Header" theme that comes with IntelliJ. I wonder if IntelliJ incorrectly recognizes Catppuccin Latte as a dark theme.

**Comment by sgoudham** [comment]
I can reproduce this on the `Xcode Light` theme too so I'm inclined to believe that this is a bug introduced by JetBrains in 2023.3.1

**Comment by sgoudham** [comment]
Hi again @ftqo 

Could you confirm for me if you're still running into this issue in **IntelliJ IDEA 2024.1**?

I've recently upgraded and it seems to have resolved itself.

**Comment by ftqo** [comment]
Yes, it seems to have resolved itself.
