### ISSUE TITLE
Accessibilty: Change unused variable color

### ISSUE THREAD

**Issue by sarowarhosen03** [catppuccin/jetbrains#119]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

![Screenshot from 2024-01-12 17-52-53](https://github.com/catppuccin/jetbrains/assets/98280301/b483a72b-4eaf-4a3a-81f4-93f9a112587f)
is this color isn't annoying , i hope you willl fix it

**Comment by quentinguidee** [comment]
Could you be more specific about the issue in this screen? I'm not sure what is the problem in the screenshot. Is that an accessibility issue? Is that a preference issue? Why would you like this change? What alternative do you want? etc.

**Comment by sarowarhosen03** [comment]
> Could you be more specific about the issue in this screen? I'm not sure what is the problem in the screenshot. Is that an accessibility issue? Is that a preference issue? Why would you like this change? What alternative do you want? etc.

I think it's an accessibility tissue. With this color of unused variable it's hard to read them

**Comment by sgoudham** [comment]
Hey :wave: 
Sorry for taking so long to reply. 

Unfortunately, I tried to find out what the key is called in the exported XML file but I can't see it anywhere :pensive: 

The workaround for this is to change the values by heading into into `Settings` -> `Editor` -> `Color Scheme` -> `General` -> `Errors and Warnings` and click on `Unused Code`:

![image](https://github.com/catppuccin/jetbrains/assets/58985301/2e820624-8d41-45a8-83ef-3e75f2a33b3f)

I'll try to spend more time later on finding the key :+1:

**Comment by uncenter** [comment]
Found the key! It is `NOT_USED_ELEMENT_ATTRIBUTES`. I found it relatively easy to find the key for a UI element if it is in the settings by:
1. Setting the UI element to some random hex value, and copy the hex value.
2. Apply settings, then export to `.icls`.
3. Search resulting export file for the hex copied in step 1.

**Comment by uncenter** [comment]
Looks like we already have it, but as surface2: https://github.com/catppuccin/jetbrains/blob/0a79b592fd9810c08bb96d9bd18bff93d3856943/generateFlavours/editor.xml#L2033

Maybe overlay2/subtext0 instead?
