### ISSUE TITLE
Latte theme: Very low contrast of highlighted search terms in the Search Everywhere window

### ISSUE THREAD

**Issue by t-bowersox** [catppuccin/jetbrains#123]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

When you have the Latte theme applied, open the "Search Everywhere" window (i.e. pressing Shift twice) and start searching for something.

You should notice that the highlighted matches in the search results have very low contrast and are hard to read.

I checked the colors from the screenshot in the [WebAIM contrast checker](https://webaim.org/resources/contrastchecker/?fcolor=4D4F67&bcolor=7D3EE8) and the ratio is only 1.41:1. Ideally, the contrast ratio should be 4.5:1.

### Attach screenshots.

<img width="358" alt="Screenshot 2024-02-26 at 2 22 21 PM" src="https://github.com/catppuccin/jetbrains/assets/11789189/a7487bb6-6c17-47ad-ada8-c469c4fad39d">

### What IDE(s) are you seeing the problem on?

WebStorm 2023.3.4

**Comment by enidisepic** [comment]
I looked into this and it is indeed not possible to change the foreground color of `SearchMatch`. However, if that is a possible change, other background colors would offer a higher contrast ratio:

| Color(s) | Example | Contrast Ratio |
|--------|--------|--------|
| Yellow | ![Example](https://place-hold.it/50/df8e1d/4c4f69.png?text=test) | 3.05 |
| Rosewater, Pink | ![Example](https://place-hold.it/50/dc8a78/4c4f69.png?text=test) ![Example](https://place-hold.it/50/ea76cb/4c4f69.png?text=test) | 3.02 |

<details>
  <summary>Click here for the other colors</summary>

  Colors that have been omitted:

  | Color(s) | Example | Contrast Ratio |
  |--------|--------|--------|
  | Sky | ![Example](https://place-hold.it/50/04a5e5/4c4f69.png?text=test) | 2.85 |
  | Flamingo, Peach | ![Example](https://place-hold.it/50/dd7878/4c4f69.png?text=test) ![Example](https://place-hold.it/50/fe640b/4c4f69.png?text=test) | 2.67 |
  | Sapphire | ![Example](https://place-hold.it/50/209fb5/4c4f69.png?text=test) | 2.54 | 
  | Lavender| ![Example](https://place-hold.it/50/7287fd/4c4f69.png?text=test) | 2.50 |
  | Green | ![Example](https://place-hold.it/50/40a02b/4c4f69.png?text=test) | 2.38:1 |
  | Teal | ![Example](https://place-hold.it/50/179299/4c4f69.png?text=test) | 2.13:1 |
  | Maroon | ![Example](https://place-hold.it/50/e64553/4c4f69.png?text=test) | 2.03:1 |
  | Blue | ![Example](https://place-hold.it/50/1e66f5/4c4f69.png?text=test) | 1.62:1 |
  | Mauve, Red (Status Quo) | ![Example](https://place-hold.it/50/8839ef/4c4f69.png?text=test) ![Example](https://place-hold.it/50/d20f39/4c4f69.png?text=test) | 1.47:1 |
</details>

On the other hand, this might break contrast with other themes but it took me over 40 minutes to create the table so I'll post this comment anyways.
