### ISSUE TITLE
New terminal background is unstyled

### ISSUE THREAD

**Issue by VindicoShaun** [catppuccin/jetbrains#127]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

Hi! Appears to be a bit of a problem with some colour blocks not getting the colors applied any more after updating Webstorm to 2024.1, unsure if it happens to other JetBrains products. Thanks :)

### Attach screenshots.

![image](https://github.com/catppuccin/jetbrains/assets/90326453/9110801b-1354-465b-8fc2-ccd886f255ec)

### What IDE(s) are you seeing the problem on?

Intellij Webstorm 2024.1

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks for raising this. Long story short - **I can't see how to theme it at the moment.**

When looking at the editor through the [UI Inspector](https://plugins.jetbrains.com/docs/intellij/internal-ui-inspector.html#enabling-the-ui-inspector), the `background` seems to default to `#1E1F22` and doesn't inherit the `Panel.background` colour that I've set:

![image](https://github.com/catppuccin/jetbrains/assets/58985301/c46b2d43-e718-45e1-91e0-3084a01cc00d)

I'm also unable to get code completion on the user interface keys in the newer version as per [their documentation](https://plugins.jetbrains.com/docs/intellij/themes-customize.html#finding-a-ui-control-key-using-code-completion-in-the-editor) so I'm honestly pretty frustrated :/

Have you found other themes that have been able to theme the background? If so, please do link them as I might be able to dig through their source code (if available) to see what keys they are using.

Unfortunately, the only advice I can offer at the moment is that you disable the new terminal in the settings, sorry!

**Comment by dicedpixels** [comment]
Seems like there's still theming issues with the new terminal:
[New terminal: colors are not consistent with Darcula theme](https://youtrack.jetbrains.com/issue/IDEA-349150/New-terminal-colors-are-not-consistent-with-Darcula-theme)

Even their own high contrast theme is inconsistent:
![image](https://github.com/catppuccin/jetbrains/assets/121529979/1570ef66-184f-4a10-9ba7-ef60a7a00272)

**Comment by dicedpixels** [comment]
New update out: https://youtrack.jetbrains.com/articles/IDEA-A-2100661951/IntelliJ-IDEA-2024.1.1-241.15989.150-build-Release-Notes

Several changes/fixes to new terminal.
