### ISSUE TITLE
Missing color for the current branch in git log

### ISSUE THREAD

**Issue by IShungite** [catppuccin/jetbrains#130]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

There is no color for the current branch in the git log

Latte theme
![image](https://github.com/catppuccin/jetbrains/assets/56173955/8cd5776f-b83a-4974-808d-efb5ffcf08e2)

Light theme
![image](https://github.com/catppuccin/jetbrains/assets/56173955/6094aedd-ddd5-4736-86ea-30d5b6cb6f09)

### What IDE(s) are you seeing the problem on?

PhpStorm 2024.1 - Build #PS-241.14494.237

**Comment by sgoudham** [comment]
Hi :wave: 
Thanks for bringing it to my attention. 

I've been playing about locally and using the accent colour `mauve` to try and improve this. I've got this at the moment:

![image](https://github.com/catppuccin/jetbrains/assets/58985301/987a99d3-c4ff-4800-9120-f71d221fed7a)

Unfortunately, I'm unable to override the selection highlight for some reason, resulting in the jarring grey colour compared to the light-ish purple. This is even worse on dark modes:

![image](https://github.com/catppuccin/jetbrains/assets/58985301/a83c27fc-d475-4292-a710-9ca10bf96ba9)

I'd like to have the purple-ish accent colours but the selection highlight sort of ruins. I'll try to make the current branch colour another variation of grey and see how that looks :+1:
