### ISSUE TITLE
Increase file colour contrast for dark flavours (frappe, macchiato & mocha)

### ISSUE THREAD

**Issue by connrs** [catppuccin/jetbrains#134]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

For your consideration: I believe it would be very helpful if the contrast between the Orange and Rose colours when configuring file colors could be widened a little so that they are easier to distinguish.

I use file colors to ensure that different scopes of my projects are highlighted with a traffic light scheme so I can distinguish between low/medium/high risk code.

The orange and rose colours are very close and it is hard for me to distinguish between the two when inside any of the dark mode UI themes (I <3 Frappe when I'm in the mood for dark mode.) 

Catpucchin Latte however is *chefs kiss* as the contrast is wonderful. I'm currently sticking to light mode (oh, the humanity) at the moment as I'm working on a project which requires me to pay attention to this traffic light scheme of scopes.

I appreciate that this may be a difficult request to satisfy as you need to balance contrast with the theme itself.

**Comment by sgoudham** [comment]
Hey :wave: 

Thanks for bringing this to my attention, I don't have file colours enabled so I wasn't aware of it. I'm focusing on other parts of the Catppuccin organisation at the moment but I'd appreciate a PR to increase the contrast for the darker flavours. 

I believe the values listed below need to be tweaked: https://github.com/catppuccin/jetbrains/blob/1f1a20e98ac63df91ac52a7987d707b56bbdd480/generateFlavours/ui.theme.json#L182-L188

Happy to accept a PR that updates the values listed above and with before/after screenshots!

**Comment by connrs** [comment]
Hey @sgoudham,

Thanks for this (especially the hint about what needs altering.) 

I will have a look over the next few weeks and see if I can make some adjustments. If I can make it look even half decent then I'll submit a PR and see what you think.

**Comment by sgoudham** [comment]
No worries! I'm happy to assist if you want to provide updates here. 

Make sure to read the [CONTRIBUTING.md](https://github.com/catppuccin/jetbrains/blob/main/CONTRIBUTING.md) which should hopefully answer some questions around project setup, also happy to explain anything further in this issue if need be!
