### ISSUE TITLE
Missing colour in project tabs

### ISSUE THREAD

**Issue by lauragra-y** [catppuccin/jetbrains#135]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

In MacOS the user can merge multiple project windows into one window as tabs. The background colour of the currently selected project tab is not themed correctly.

The same issue also applies to the horizontal scrollbar when the user has many file tabs open within a project.

### Attach screenshots.

Selected project tab has a grey/green background:
<img width="1446" alt="image" src="https://github.com/catppuccin/jetbrains/assets/48514017/bd6bd578-f1b8-4f9b-a653-f4af75d8311c">

Horizontal scroll bar for file tabs has the same grey/green colour:
<img width="1446" alt="image" src="https://github.com/catppuccin/jetbrains/assets/48514017/0ad4fd76-0094-4aea-8a78-64435e1f7da0">

### What IDE(s) are you seeing the problem on?

PyCharm 2024.1.1 (Community Edition)

**Comment by sgoudham** [comment]
Hey 👋,
Sorry for not replying on this issue earlier.

Fixing this is a matter of finding the key for the project tab colours and editing the, I would assume, `ui.theme.json` file in the repository.

I don't have time to work on this repository at the moment so more than happy to accept a PR!

**Comment by gquittet** [comment]
Hello @sgoudham 👋 

I will make a pull request this evening with pleasure!

And thank you for this awesome theme 🙏

**Comment by gquittet** [comment]
@sgoudham I just made a pull request to fix this issue: https://github.com/catppuccin/jetbrains/pull/179
