### ISSUE TITLE
Yellow scrollbar on macOS

### ISSUE THREAD

**Issue by niallobrien** [catppuccin/jetbrains#157]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

When scrolling in certain windows, I see a thick yellow scrollbar, but don't see any theming options to customise this in any way (size or colour). Am I missing something here?
Thanks!

![Screenshot 2024-07-31 at 09 54 07](https://github.com/user-attachments/assets/36845a5a-b782-45e3-986b-c9e107a7abda)

**Comment by sgoudham** [comment]
Hey :wave:,

So the variables for theming the Scrollbar seem to be implemented in the `ui.theme.json` shown below, where `secondaryAccentColor` is yellow:

https://github.com/catppuccin/jetbrains/blob/c05b72dcbf2976a0c9adc399952c97f70382dd3a/generateFlavours/ui.theme.json#L323-L330

This isn't customisable through the IDE and would require compiling and building the plugin yourself to change this value. As a side note, I'm not sure why we override it to be yellow on macOS only, think it's best to make it the same as what's specified in the `editor.xml`:

https://github.com/catppuccin/jetbrains/blob/c05b72dcbf2976a0c9adc399952c97f70382dd3a/generateFlavours/editor.xml#L73-L76

It seems like there are conflicting configurations in these two files for macOS, which I'm honestly not sure how that's ended up like that. I think it would be best to make the colour the same across all 3 operating systems.

**Comment by ForsakenHarmony** [comment]
Any chance this will be fixed soon?

**Comment by sgoudham** [comment]
I'll have a look this weekend, should be an easy fix but honestly forgot about it!
