### ISSUE TITLE
Incompatible: requires IDE build 241.* or erlier

### ISSUE THREAD

**Issue by Lzyct** [catppuccin/jetbrains#158]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

`Catppuccin Icons v1.6.0` is not compatible with IntelliJ IDEA 2024.2

![image](https://github.com/user-attachments/assets/ec6969d1-4769-45bb-a279-e0ca75e84979)

### Attach screenshots.

![image](https://github.com/user-attachments/assets/69af61f6-1f95-4383-a6e5-9512552315e2)

### What IDE(s) are you seeing the problem on?

IntelliJ IDEA 2024.2 (Community Edition)

**Comment by sgoudham** [comment]
Hey :wave: 

This is the repository for the theme, not the plugin. See https://github.com/catppuccin/jetbrains-icons/issues/79 which is tracking support for 2024.2 in our icons plugin.
