### ISSUE TITLE
Weird text rendering while hovering on attribute proc macros in RustRover

### ISSUE THREAD

**Issue by AnkurMal** [catppuccin/jetbrains#160]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

While hovering on the attribute proc macro, the text rendering for parenthesis is weird in the code section of the macro's doc comment.

### Attach screenshots.

![image](https://github.com/user-attachments/assets/567c11c4-b337-41b9-9a47-d028018a2140)

### What IDE(s) are you seeing the problem on?

RustRover 2024.1.8

**Comment by sgoudham** [comment]
Hey :wave:,

I can't reproduce this on RustRover 2024.2 EAP:

![image](https://github.com/user-attachments/assets/d08e01e1-8608-4e45-a2a8-6993ebcf3262)

I also fail to see how this is a problem of the colourscheme as the plugin is purely focused on syntax highlighting. I'd imagine it's a bug in the RustRover IDE itself, I'd encourage you to report it to them :+1:
