### ISSUE TITLE
the macchiato theme in android studio is broken..it is not looking as it was..

### ISSUE THREAD

**Issue by aniruddha81** [catppuccin/jetbrains#164]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Have you followed the instructions in the the pinned issue?

- [X] I have followed the instructions in the pinned issue and they do not solve my problem.

### Describe your problem.

the macchiato theme is broken

### Attach screenshots.

![Screenshot_20240825_180559](https://github.com/user-attachments/assets/cc1ca7c3-c17c-444f-b6c6-17a0c31ff18b)

### What IDE(s) are you seeing the problem on?

Android Studio

**Comment by sgoudham** [comment]
Please see the pinned issue (#97)

**Comment by aniruddha81** [comment]
solved..thanks
