### ISSUE TITLE
Current symbol lines are have low constrast in the scrollbar

### ISSUE THREAD

**Issue by kjnsn** [catppuccin/jetbrains#166]
### Describe your problem.

The contrast of the lines for the currently selected symbol is difficult to distinguish, especially if there are other warnings in the file.

### Screenshots.

| Default | Dracula |  Catppuccin Mocha |
| ------------- | ------------- | ------------- |
| <img width="645" alt="Screenshot 2024-08-28 at 9 18 06 PM" src="https://github.com/user-attachments/assets/6873cf87-2114-4f9c-a74d-95565b491ab7"> | <img width="627" alt="Screenshot 2024-08-28 at 9 16 03 PM" src="https://github.com/user-attachments/assets/4b2bfa6b-7d95-4e27-a3bf-6021c7f8f7ce">|<img width="655" alt="Screenshot 2024-08-28 at 9 16 51 PM" src="https://github.com/user-attachments/assets/9f5c7327-86b3-439f-91ff-4318b9ba8e4d"> | 

### What IDE(s) are you seeing the problem on?

IntelliJ IDEA 2024.2.0.2 (Community Edition)

**Comment by kjnsn** [comment]
Here's a better example. The variable I selected has 5 lines in the scrollbar, but between all the errors and warnings it's hard to see

<img width="98" alt="Screenshot 2024-08-29 at 7 12 00 PM" src="https://github.com/user-attachments/assets/1ffab8cc-52c4-43a7-afa9-045df6ed4868">

**Comment by kjnsn** [comment]
This is the relevant XML key: https://github.com/catppuccin/jetbrains/blob/9ff16a8d0f81e4102ef441f200697d9914178353/generateFlavours/editor.xml#L1387

**Comment by mnemotic** [comment]
Is there anything I can do to contribute to troubleshooting this issue?
