### ISSUE TITLE
Any plans to support "Frappé" variant

### ISSUE THREAD

**Issue by mittalyashu** [catppuccin/jetbrains#18]
The "Frappé" variant is available in VSCode theme, but there was only single-default variant theme in JetBrains.

**Comment by nekowinston** [comment]
Hi there :wave:

JetBrains still implements the 0.1.3 Catppuccin spec as of now.
We currently have https://github.com/catppuccin/jetbrains/pull/15 open, which implements 0.2.0, but it's not fully ready for release just yet.

I'd like to track this in a single issue if possible, which would be https://github.com/catppuccin/jetbrains/issues/10

**Comment by mittalyashu** [comment]
Great, thanks :)
