### ISSUE TITLE
Marketplace upload

### ISSUE THREAD

**Issue by tiepp** [catppuccin/jetbrains#2]
In order to make the theme easier available it would be nice to publish it on the [Jetbrains Marketplace](https://plugins.jetbrains.com/).

The initial upload has to be done manually with a Marketplace account. Updates can be published via gradle using a token.

If an org (email-)account is not yet available, I'd offer to upload with my account as according to [this post](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206767755-What-is-the-best-way-to-share-plugin-ownership-) ownership can be transferred later on.

@Pocco81

**Comment by tiepp** [comment]
I plan to fix some issues and upload to the Marketplace today.

**Comment by conifer-dev** [comment]
FYI the newest push says its been uploaded to the Marketplace, but it's not there.

**Comment by tiepp** [comment]
There you go 🙃

https://plugins.jetbrains.com/plugin/18682-catppuccin-theme
