### ISSUE TITLE
[Bug] Selection is not clearly visible when selecting a single line. 

### ISSUE THREAD

**Issue by ghostx31** [catppuccin/jetbrains#21]
The selection is clearly visible when selecting multiple lines. 
![Screenshot from 2022-10-23 16-44-33](https://user-images.githubusercontent.com/68803793/197388904-ff3bbcdc-2449-4648-960f-98b6b4ca5f55.png)

But the selection is barely visible when selecting a line. The selection background can be made lighter or darker to make the selection more legible. 
![Screenshot from 2022-10-23 16-45-05](https://user-images.githubusercontent.com/68803793/197388921-4784a4db-1465-46a1-ad9d-3e3f034ed9ef.png)

This behaviour is only true for the dark flavours. The selection looks good on latte.

**Comment by sgoudham** [comment]
Yeah I was wanting to revisit this, I think we should be making it lighter for the currently selected.

For anyone else looking at this, the relevant section of the code is [here](https://github.com/catppuccin/jetbrains/blob/main/generateScheme/template.xml#L64-L68). Should also be a somewhat easy fix, just requires some playing about with!
