### ISSUE TITLE
Highlighting comments makes them unreadable

### ISSUE THREAD

**Issue by christopherdmgunn** [catppuccin/jetbrains#24]
When selecting comments they become unreadable.

All three dark modes:

![image](https://user-images.githubusercontent.com/69153678/198256899-ebecdaec-522e-4962-bd78-04e437a26d88.png)

Light Mode
![image](https://user-images.githubusercontent.com/69153678/198257654-e9d82b9b-3c0b-4f23-a45c-94cc9145d6b4.png)

Is there a way to dynamically change comment colour based on highlight to account?

**Comment by sgoudham** [comment]
Hey 👋, thanks for raising this. 

On my installation, the highlights currently look like this: 

`Mocha`
![image](https://user-images.githubusercontent.com/58985301/198262432-fb9874c5-aae6-4966-af50-9bb85c29483e.png)

`Latte`
![image](https://user-images.githubusercontent.com/58985301/198262892-ad3779d4-b860-4528-9a2a-eeab7b3db4e0.png)

which don't seem nearly as bad as the highlights raised in your issue. Could you please screenshot your settings like mine down below? 

The path is `File > Settings > Editor > Color Scheme > General`
Within the highlight box, it should be `Editor > Selection Foreground`
![image](https://user-images.githubusercontent.com/58985301/198263215-93c611e4-c26c-4447-aa29-c6b8388a0b3a.png)

**Comment by christopherdmgunn** [comment]
Hi please find attached for both latte and mocha. No settings have been changed and the restore defaults setting is not selectable as nothing has been changed.
![Catpuccin bug 2](https://user-images.githubusercontent.com/69153678/198269041-6ec6a812-dd8d-4f6a-8da0-3efdb2805445.png)
![Catpuccin bug 2 1](https://user-images.githubusercontent.com/69153678/198269047-58594701-83e2-45be-9f4b-5efbd33c683c.png)
![Catpuccin bug 2 2](https://user-images.githubusercontent.com/69153678/198269048-fe1eeec6-1e52-4101-a667-01e70c3e72fa.png)

**Comment by christopherdmgunn** [comment]
Sorry realised I hadn't applied mocha but the contents are still the same 
![image](https://user-images.githubusercontent.com/69153678/198269449-97eb561a-7fed-4006-a769-decb0a965f8a.png)

**Comment by sgoudham** [comment]
Huh that's quite interesting, I can reproduce it on my local installation now but when debugging the code (running another IDE for development)... it works as expected o.o

I think I'll need to do some extra digging on this!

**Comment by sgoudham** [comment]
This should be closed with the release of [`v2.0.2](https://github.com/catppuccin/jetbrains/releases/tag/v2.0.2)!

Please allow up to 2 business days for it to appear on the marketplace! If you can't wait, you can download the jar from the release and import it into your IDE. Thanks again for raising this!
