### ISSUE TITLE
[DataGrip] Can not see text in tab name

### ISSUE THREAD

**Issue by haunt98** [catppuccin/jetbrains#28]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/5424272/200235511-ee9f0afb-e0a9-4395-aa16-20432572077f.png">

As you can see, the text `ekyc_info_2022...` is hard to see

Update: seem like sql tab name is normal, but table tab name is not

<img width="459" alt="image" src="https://user-images.githubusercontent.com/5424272/200236360-ea5e3ea5-eec0-45f1-a006-91a40d474128.png">

I use DataGrip 2022.2.5

<img width="547" alt="image" src="https://user-images.githubusercontent.com/5424272/200235611-42696df8-ed3d-40f4-8070-c7443a7816f9.png">

Theme version 2.0.3

<img width="499" alt="image" src="https://user-images.githubusercontent.com/5424272/200235643-d09793d0-4cde-48d9-88bd-fecc0994bfd2.png">

**Comment by sgoudham** [comment]
I agree that it can be improved. 
I will look into the highlights for this and make it more readable for the next release!
