### ISSUE TITLE
Copilot recommendation is not gray

### ISSUE THREAD

**Issue by kkrypt0nn** [catppuccin/jetbrains#29]
Seems like the recommendation of Copilot is always in pink color whereas it should be in gray color, see the difference between VSC and JetBrains, in this case IntelliJ IDEA.
| VSC | IntelliJ IDEA |
|----|---|
| <img width="460" alt="Screenshot 2022-11-07 at 17 45 17" src="https://user-images.githubusercontent.com/43011723/200367176-1f2d0d7f-9ad6-4635-b14e-7e51d85d9bbe.png"> | <img width="469" alt="Screenshot 2022-11-07 at 17 48 01" src="https://user-images.githubusercontent.com/43011723/200367252-c6f0478a-12cb-4573-9b06-a904308ab575.png"> |

**Comment by sgoudham** [comment]
Oh, that's interesting!
I'll look into the highlights for this for the next release!

**Comment by sgoudham** [comment]
After downloading Copilot, it looks like the colour is inherited from `Text Without Background` in the editor schema. However, you can manually override the colour by ticking the box and picking a hex value.

![image](https://user-images.githubusercontent.com/58985301/200695017-8a487fcc-c9d6-4cf5-a5d6-831f96cd0b73.png)

I'd advise you do this as a current workaround while the next release will change the highlight of `Text Without Background` to be grey @kkrypt0nn

**Comment by kkrypt0nn** [comment]
Working perfectly with that, thanks a lot! Looking forward at the update ^^
