### ISSUE TITLE
Highlighting open/close tokens is the same color as cursor

### ISSUE THREAD

**Issue by jolheiser** [catppuccin/jetbrains#3]
The highlighted open/close token boxes are the same color as the cursor, which can make for an awkward experience with methods/functions.

![catppuccin](https://user-images.githubusercontent.com/42128690/155548123-4e041c35-1b07-48c4-bffe-6ad478ae2279.png)
![foo](https://user-images.githubusercontent.com/42128690/155548650-abe39757-a2b0-4337-812b-1d975db7410b.png)

![darcula](https://user-images.githubusercontent.com/42128690/155548129-847a3c28-a762-4475-98e8-e1ca1b9cd067.png)
![foo-darc](https://user-images.githubusercontent.com/42128690/155548777-2efc95ad-0316-42ac-aec4-0af2690ea22a.png)

**Comment by tiepp** [comment]
Yeah, I have that and a couple of other issues on my list. Expect a release later that day! 😉

**Comment by jolheiser** [comment]
Wonderful, nice to hear! Such a fantastic theme! :heart:

I started to look at it myself, but I am woefully bad at UI and colors. 😅

**Comment by jolheiser** [comment]
Fixed by https://github.com/catppuccin/jetbrains/commit/dd972bd377c81cc9335b88d21a89b737d62451e1

Looks great!
![fix](https://user-images.githubusercontent.com/42128690/155598821-a58c157d-c8b3-4f4f-9dc5-167493327841.png)
