### ISSUE TITLE
Matching parenthesis are not visible enough

### ISSUE THREAD

**Issue by rcapraro** [catppuccin/jetbrains#35]
Hi,
First of all, I wanted to thank you for this theme that I use daily 👍🏻 
A little problem of visibility with the parenthesis and brackets though. The matching should be more visible (maybe add a border?)

![image](https://user-images.githubusercontent.com/245490/202519483-48a09104-b2f9-42f8-bce0-68280138d3e9.png)

Kind regards,
Richard

**Comment by sgoudham** [comment]
Hi there! Thanks for raising this. 

I agree. It should be highlighted better for better visibility. The VSCode port currently highlights a border around the matching token, so I'll implement that for the next release! I hope I can work on it this weekend and get a new release out soon!

**Comment by rcapraro** [comment]
Thx a lot !
