### ISSUE TITLE
Refactor error messages are not visible enough

### ISSUE THREAD

**Issue by rcapraro** [catppuccin/jetbrains#39]
Hi there ;-)
I noticed that when a refactoring action is not possible, the error message is not visible enough (maybe you should change the font color ?)

exemple: trying the action "Convert parameter to underscore section" which is impossible on this scala function:
![Capture d’écran 2022-11-19 172351](https://user-images.githubusercontent.com/245490/202861198-35dfe615-8a14-4d79-8b87-ae87008e15dd.png)
gives the following error message:
![Capture d’écran 2022-11-19 172414](https://user-images.githubusercontent.com/245490/202861200-1719647d-00f6-4f45-bd49-304d8f80c944.png)

Kind Regards,
Richard

**Comment by sgoudham** [comment]
Hi again! I was wondering when this would be raised 😅 

100% agree that it's not readable and should be fixed. I tried to find the relevant highlights before the 0.2.0 release, and I _just couldn't_. I think it makes sense to darken the background or make the font darker! 

Unfortunately, I'm pretty busy until the end of November, but hopefully can get around to it afterwards (or if anyone else sees this and wants to fix it, it would be much appreciated ❤️)

**Comment by sgoudham** [comment]
Since [2022.3 is about to be released](https://blog.jetbrains.com/idea/2022/11/intellij-idea-2022-3-release-candidate/), I'll cut a new release `v2.0.5` without a fix for this but include it in a later milestone/release.

**Comment by sgoudham** [comment]
So we kinda screwed up the `v2.0.5` release 😅 
Going to push this back to `v2.0.7`. Sorry about that!

**Comment by rcapraro** [comment]
No worries 🙂
Thank you for the update, i'm looking forward to the 2.07 release 👍

**Comment by sgoudham** [comment]
Hey again :wave:

I just had some free time to take a look at this. I found the highlight but unfortunately cannot edit the foreground colour to keep the pastel red in the error hint. (It might be possible but I couldn't find a way after a while of digging away at it and got pretty frustrated :sweat_smile:)

I think modifying all the dark variants to have the stock red and leaving latte untouched sounds like a good workaround to it. I've included the pics below, what do you think?

`Frappe/Macchiato/Mocha`
![image](https://user-images.githubusercontent.com/58985301/210189035-e9c83388-1ae3-49d5-8163-d240db21bab4.png)

`Latte`
![image](https://user-images.githubusercontent.com/58985301/210189068-c8028726-ec87-4247-880c-4b619815d198.png)

**Comment by rcapraro** [comment]
Hi,
it's very nice like that, thanks for the fix ;-)
