### ISSUE TITLE
New UI and Latte Theme

### ISSUE THREAD

**Issue by JediMan0308** [catppuccin/jetbrains#42]
When using the new UI and Latte theme, the text above is not clear.

Please refer to the image, thank you!!! 

<img width="546" alt="CleanShot 2022-12-07 at 08 25 13@2x" src="https://user-images.githubusercontent.com/115527381/206056492-e0fd881d-8177-4867-9e84-3efe7665b6d2.png">

**Comment by sgoudham** [comment]
Hi there :wave: Thanks for raising this!

We'll try and get this fixed for our next release! I'm unfortunately quite busy and will be for the next month or so. I'll get around to it whenever I can but sadly won't be able to provide an ETA.
