### ISSUE TITLE
[Suggestion] Breakpoint line background can be switched with execution point 

### ISSUE THREAD

**Issue by mahendranv** [catppuccin/jetbrains#47]
**Current configuration:**
<img width="659" alt="image" src="https://user-images.githubusercontent.com/6584143/214607328-38754ada-3217-4ea3-88e2-09e290d86a48.png">

line 42 is breakpoint
line 46 is execution point

But at a glance, focus goes to line 42.

**Proposed:**
Rather, breakpoint background can be removed as we already have indicator next to line number. And give the background to execution point.
<img width="592" alt="image" src="https://user-images.githubusercontent.com/6584143/214608442-3317a675-5940-4a3c-90ac-ce6d966936d4.png">

**Comment by sgoudham** [comment]
Hey there :wave: 
Sorry for the wait on the response, been pretty busy and haven't had time to focus on this. 

We've been recently discussing this internally too for VSCode and it looks like we're going to use this as the default going forward:
![image](https://user-images.githubusercontent.com/58985301/218360572-e3f4ba1d-f745-4b5a-bc4a-7f3b18c0fd86.png)

Of course, these highlights are *extremely* configurable on the client side too, feel free to change them around!
`Settings -> Editor -> Color Scheme -> Debugger`
![image](https://user-images.githubusercontent.com/58985301/218360642-abc93c06-0b3a-4d09-b8b5-2a4cbeb69420.png)

Let us know what you think!

ref: https://github.com/catppuccin/jetbrains/commit/4bfddc34b9b6a78ae822d924690e97ac797bbccf

**Comment by mahendranv** [comment]
Thanks for responding. Above looks good!!
