### ISSUE TITLE
2022.1 is not supported

### ISSUE THREAD

**Issue by ofseed** [catppuccin/jetbrains#5]
It seems to work well with IntelliJ IDEs 2022.1 version like DataGrip, but every time restarts the IDE,
there will be a message that says this plugin does not support the newer version.
![image](https://user-images.githubusercontent.com/61115159/162375432-451ed8b9-1193-4a1e-ba41-15738dd30d70.png)

**Comment by tiepp** [comment]
Good to hear it works with 2022.1. 
I'll check on the RC and update the metadata asap. 
Thanks for the report!

**Comment by tiepp** [comment]
1.0.5 is available now
