### ISSUE TITLE
Fleet Support

### ISSUE THREAD

**Issue by BlueFalconHD** [catppuccin/jetbrains#50]
Jetbrains Fleet doesn't have marketplace support yet, and uses .json files for the themes. Any plans to support it?

**Comment by ghostx31** [comment]
@nekowinston had started working on it and seems like it uses texmate for themes which is completely different from the way JB IDEs have themes. I'd say open a discussion on the main repo to track this.

**Comment by nekowinston** [comment]
It's sadly outside the scope of this repo. Fleet shares pretty much nothing in common with the IDE themes. 

As @ghostx31 said, we'll make a new port specifically for JetBrains fleet once it's documented. The whole syntax parser, plugin format, and distribution are different to the classic JB IDEs.

**Comment by nekowinston** [comment]
Created a discussion on the main repo: https://github.com/catppuccin/catppuccin/discussions/1893
