### ISSUE TITLE
Suggestion: variants that don't use italics

### ISSUE THREAD

**Issue by enxg** [catppuccin/jetbrains#56]
I find italics a little hard to read and I mostly stay away from themes with italic styles. I liked this theme and I really want to use it but italics are making it hard for me. I'm pretty sure this is not just me and it would be nice if this theme had variants that didn't use italics.

**Comment by sgoudham** [comment]
Hey 👋 @enxg 

There are non-italic versions bundled with the theme, you can read the usage or getting started section to understand how to apply them!

![Screenshot_2023-03-11-18-01-29-79_984e1414ae90666a90f12ff17ec14a7f](https://user-images.githubusercontent.com/58985301/224504484-ebb6e086-37f8-450d-b154-b93318e0f43c.jpg)

**Comment by enxg** [comment]
oh I didn't see that, thanks
