### ISSUE TITLE
Cappuccin Latte terminal standard output color is too light of a shade of gray

### ISSUE THREAD

**Issue by Samasaur1** [catppuccin/jetbrains#57]
I have the plugin installed, and when I have catppuccin-latte selected, it makes the builtin terminal standard output a very light shade of gray (BCC0CC):.stdout: BCC0CC ANSI black: 5C5F77

<img width="714" alt="very light text" src="https://user-images.githubusercontent.com/30577766/224455307-9fe0f460-8518-4895-95fc-4c9b48c3244a.png">

I think it should _at least_ be using a shade as dark as the ANSI black shade (5C5F77):

<img width="709" alt="darker text" src="https://user-images.githubusercontent.com/30577766/224455394-d058ef0a-7c9d-49d3-949a-b5e9b1eea249.png">

I checked the styleguide, and [it seems to say](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#terminals) that `text` should be used, rather than `subtext1`, which is the ANSI black color.

Whatever the new color picked is, it should definitely be darker than the current color.

**Comment by Samasaur1** [comment]
I'm pretty sure the solution is to change line 306 in `generateFlavours/template.xml` from this:

https://github.com/catppuccin/jetbrains/blob/39805f743d6c2b73197431e8dd0bc57f1d14aedf/generateFlavours/template.xml#L304-L308

to `<option name="FOREGROUND" value="{{text}}"/>`.

However, I haven't tested this, so I'm not creating a PR.

**Comment by nekowinston** [comment]
Thanks for the details, it seems that I introduced that with #36.
I tried to match the 0-15 terminal colors, but didn't notice that the foreground color itself was impacted - sorry about that.
