### ISSUE TITLE
options menu icon area is weired

### ISSUE THREAD

**Issue by dragove** [catppuccin/jetbrains#69]
![image](https://user-images.githubusercontent.com/24190403/233559022-c8a07148-9fd0-462c-8549-9a2098aa039a.png)

**Comment by darkenmay** [comment]
@dragove it is regression and should be fixed in the next release of IDEA. Details here https://youtrack.jetbrains.com/issue/IDEA-316472/Welcome-Screen-settings-icon-background-regression-with-custom-theme

**Comment by dragove** [comment]
Thanks for telling me that, I'll close this issue as it is not caused by the theme.
