### ISSUE TITLE
Issues with the DataGrip plugin

### ISSUE THREAD

**Issue by ysooqe** [catppuccin/jetbrains#72]
First of all, amazing theme, thank you!

Unfortunately, there are two issues when using the JetBrains DataGrip plugin (to work with databases).

Regarding the first one:
I usually write SQL queries in the query console.
When you have nested queries (like a simple SELECT subquery) and you are trying to execute them using Ctrl+Enter, DataGrip visually highlights the query that is to be executed (either just the nested one or the entire query).
Using the Catppuccin theme (Macchiato in my case), this visual highlighting does not work anymore.

Regarding the second one:
I have all my connections color-coded in order to visually highlight the connection I am currently using.
Unfortunately, Catppuccin does not play well with the predefined (and unchangeable) colors that DataGrip offers to color-code connections. Text is not very readable (the contrast between the colors and the themed text color is pretty low).

It would be great if those two things would also work well when using Catppuccin since it is a really pleasent theme!

Please let me know if you need any further information regarding these issues.

**Comment by sgoudham** [comment]
Hiya 👋 

I'm really sorry but I haven't had the time to work on this & I'm not a DataGrip user. I'll mark this issue as `help wanted` and with a `datagrip` label to hopefully increase the visibility. I'm really sorry that I can't do more right now!

**Comment by kkrypt0nn** [comment]
Your first point should be fixed with the PR above.

Could you explain the second point a bit more precisely? Eventually with comparisons with the normal dark theme va catppuccin theme.

**Comment by ysooqe** [comment]
The first point is fixed with the PR, thank you!

The second point es slightly different now after the latest updates, so I can not give a screenshot for how it used to be.
How it used to be: Since the color of the text is slightly "pink"(ish), when you chose a red color for the database connection, text color and background color were almost the same, so the text was basically unreadable, since there was not contrast between it and its background.
This seems to have been "fixed" by making the colors that a connection can be colored with much darker when using the Catppuccin theme.

But now that they are so much darker, they can be barely separated from each other (i.e. they all look very alike and make it different to spot different database connections just by the color; which is the use case for having different colored connections in the first place).
Im not sure though if this can still be considered an issue. If it does, it might be better to open a separate issue ticket for that. So I guess this ticket could be closed.
Thank you for taking the time to submit a PR!

**Comment by sgoudham** [comment]
Hi @ysooqe, thanks for the background on the database connections.

I think it makes sense to close this issue and raise another regarding the database connections, I'd appreciate if you could use the new [Enhancement Issue](https://github.com/catppuccin/jetbrains/issues/new?assignees=&labels=enhancement&projects=&template=enhancement.yml) template for raising this! (I think it's more of an enhancement instead of a bug but feel free to raise it as a [Bug Report](https://github.com/catppuccin/jetbrains/issues/new?assignees=&labels=bug&projects=&template=bug.yml) if you think it is more of a bug than an enhancement.)

Thanks for raising this issue in the first place!

**Comment by ysooqe** [comment]
I have opened an enhancement issue here: #110
