### ISSUE TITLE
Update for 2023.2

### ISSUE THREAD

**Issue by Desoroxxx** [catppuccin/jetbrains#73]
2023.2 is just around the corner and brings awesome improvements.

It would be great if support for it could already be added so I and other using the plugin can switch when it comes out of EAP

**Comment by sgoudham** [comment]
https://github.com/catppuccin/jetbrains/releases/tag/v2.2.0 should support EAP now!
It'll be up on the marketplace when JetBrains get around to reviewing it in 1-3 business days :handshake:
