### ISSUE TITLE
Add Coverage Highlighting

### ISSUE THREAD

**Issue by thelooter** [catppuccin/jetbrains#78]
Currently there is no Coverage Highlighting in the Themes. As an example to how this could look can be found in Material theme like this:
![image](https://github.com/catppuccin/jetbrains/assets/24987877/0b1a87be-014a-484f-a4e9-d6c902e8ff49)

This would make Unit Testing a lot easier

**Comment by sgoudham** [comment]
Hiya there :wave: 

I'm currently on `v2023.2.2` and when running tests with coverage, the highlighting is actually contained within the status column shown on the left:

![image](https://github.com/catppuccin/jetbrains/assets/58985301/24a63b9d-3771-4edf-a0b5-1309989db559)

I left it like this as it matches up with the breakpoint style where it doesn't highlight the line:

![image](https://github.com/catppuccin/jetbrains/assets/58985301/ecef374e-3b4d-43dc-b392-2bc244a82f6c)

**If you would still like the entire line to be highlighted**, you can modify the `Background` for `Line Coverage` shown below inside of the `Editor > Color Scheme -> General` settings:

![image](https://github.com/catppuccin/jetbrains/assets/58985301/3d918a3a-e77f-4293-a692-724eaa75badd)
