### ISSUE TITLE
XAML Support

### ISSUE THREAD

**Issue by BButner** [catppuccin/jetbrains#8]
Using JetBrains Rider, any XAML file that gets opened is basically all orange and white, with no distinction between imports, element types, properties, strings, etc...

**Comment by tiepp** [comment]
Thanks for the report. I do not have Rider license and there seems to be no XAML plugin for IntelliJ.. Happy to accept a PR :)

In case you want to give it a try, here's some instructions 

https://github.com/catppuccin/catppuccin/issues/35#issuecomment-1030799274

**Comment by BButner** [comment]
> Thanks for the report. I do not have Rider license and there seems to be no XAML plugin for IntelliJ.. Happy to accept a PR :)
> 
> In case you want to give it a try, here's some instructions
> 
> [catppuccin/catppuccin#35 (comment)](https://github.com/catppuccin/catppuccin/issues/35#issuecomment-1030799274)

Working on this now.

There isn't specific XAML color scheme support, so I'll have to make changes to the language defaults. However looking at it (I'm just changing 2 things) it'll actually more closely match the theme in VSCode with these two small tweaks.

Expect a PR here soonest.
