### ISSUE TITLE
Support Inline Error plugin

### ISSUE THREAD

**Issue by ben-blackdice** [catppuccin/jetbrains#83]
Be nice to see some predefined colors, 

https://plugins.jetbrains.com/plugin/17302-inlineerror

**Comment by nekowinston** [comment]
I've had a look at the source code, and it might not be possible:

https://github.com/despinoza1/InlineError/blob/04d6536a5a5e2985aa3e0712a9283053f53fc75b/src/main/java/com/daniel_espinoza/inline_error/settings/InlineErrorState.java#L17-L25

**Comment by sgoudham** [comment]
Closing as colours seem to be configurable via their own plugin settings which we cannot highlight by default.
