### ISSUE TITLE
2023.3 Support?

### ISSUE THREAD

**Issue by Desoroxxx** [catppuccin/jetbrains#85]
2023.3 has entered EAP, it is a very minimal update so far, it includes UX, new defaults, and most importantly Java 21 support, I am pretty sure nothing should break from just changing the maximum supported version to it, if you want me to test a build I am available.

https://blog.jetbrains.com/idea/2023/09/intellij-idea-2023-3-eap/

**Comment by diantongren** [comment]
> 2023.3 has entered EAP, it is a very minimal update so far, it includes UX, new defaults, and most importantly Java 21 support, I am pretty sure nothing should break from just changing the maximum supported version to it, if you want me to test a build I am available.
> 
> https://blog.jetbrains.com/idea/2023/09/intellij-idea-2023-3-eap/

I tried to repackage it myself and there seemed to be no problem.

**Comment by Desoroxxx** [comment]
> > 2023.3 has entered EAP, it is a very minimal update so far, it includes UX, new defaults, and most importantly Java 21 support, I am pretty sure nothing should break from just changing the maximum supported version to it, if you want me to test a build I am available.
> > https://blog.jetbrains.com/idea/2023/09/intellij-idea-2023-3-eap/
> 
> I tried to repackage it myself and there seemed to be no problem.

Could you send it here in the meanwhile?

**Comment by diantongren** [comment]
[Catppuccin Theme-2.2.1.zip](https://github.com/catppuccin/jetbrains/files/12842140/Catppuccin.Theme-2.2.1.zip)

**Comment by sgoudham** [comment]
Hiya there :wave:, apologies for not replying to this sooner.

I've bumped up the version to support 2023.3* in https://github.com/catppuccin/jetbrains/commit/3f0c2db504ad28fd4086188bd8bdc5bda09c125f. 

We'll be releasing the next version of this theme shortly as v3.0.0 with the many UI improvements made in #89.
