### ISSUE TITLE
Mocha support for RustRover EAP

### ISSUE THREAD

**Issue by Sacro** [catppuccin/jetbrains#87]
Everything looks rather... red?

![image](https://github.com/catppuccin/jetbrains/assets/2659869/c659ef1d-9600-4abc-9d09-bbd3f216ca4f)

**Comment by sgoudham** [comment]
Hiya, it looks like you have applied the **UI Interface Theme** but haven't applied the **Color Scheme**. The Intellij documentation highlights this difference [here](https://www.jetbrains.com/help/idea/user-interface-themes.html):

![image](https://github.com/catppuccin/jetbrains/assets/58985301/e6ccfa55-cef3-4320-b6c7-72e74150bebe)

**Please see the following screenshot on how to enable the Editor theme:**

`Settings` -> `Editor` -> `Color Scheme`
![image](https://github.com/catppuccin/jetbrains/assets/58985301/4d73734c-b978-4146-b486-b35b712f89c4)

**Comment by Sacro** [comment]
Wow, I've never had to do that in any other of the Jetbrains products, it has always inherited it automatically. 

Is this something that could go on the documentation?
