### ISSUE TITLE
Mocha variant broke with 3.0.0 on IntelliJ IDEA 2023.2.2 Ultimate

### ISSUE THREAD

**Issue by kontza** [catppuccin/jetbrains#96]
Hi,

I just updated the plugin on my Idea installation. Mocha variant now has white (yuck!) code editor. I'm using the new UI.

![Screenshot 2023-10-16 at 13 32 26](https://github.com/catppuccin/jetbrains/assets/2431112/c6a625dd-a74c-48d7-a667-8a51c860c678)

**Comment by kkrypt0nn** [comment]
Hey there - please check [this reply](https://github.com/catppuccin/jetbrains/issues/87#issuecomment-1743872629) out

**Comment by kontza** [comment]
Cheers! That helped!
